# Generated by Django 5.2 on 2025-06-04 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_language_userprofile_usergenrepreference'),
        ('recommendations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Код языка')),
                ('name', models.CharField(max_length=50, verbose_name='Название языка')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='UserSurveyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_goal', models.CharField(choices=[('fun', 'Отдых/развлечение'), ('inspire', 'Вдохновение/идеи'), ('skill', 'Проф-рост'), ('study', 'Учёба/исследование')], max_length=10, verbose_name='Цель чтения')),
                ('mood_tags', models.JSONField(default=list, help_text='Список из MOOD_TAG_CHOICES', verbose_name='Предпочитаемая атмосфера')),
                ('reading_frequency', models.FloatField(choices=[(0.5, '< 1 книг/мес'), (1.5, '1–2 книг/мес'), (4.0, '3–5 книг/мес'), (6.0, '> 5 книг/мес')], verbose_name='Частота чтения')),
                ('content_filters', models.JSONField(default=list, help_text='Список из CONTENT_FILTER_CHOICES', verbose_name='Контент-фильтры')),
                ('other_content_filters', models.TextField(blank=True, help_text='Дополнительные фильтры контента, указанные пользователем', verbose_name='Другие контент-фильтры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения опроса')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('fav_authors', models.ManyToManyField(blank=True, related_name='favorite_in_survey', to='books.author', verbose_name='Любимые авторы')),
                ('fav_books', models.ManyToManyField(blank=True, related_name='favorite_in_survey', to='books.book', verbose_name='Любимые книги')),
                ('original_languages', models.ManyToManyField(to='recommendations.language', verbose_name='Предпочитаемые языки оригинала')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль читательских предпочтений',
                'verbose_name_plural': 'Профили читательских предпочтений',
            },
        ),
        migrations.CreateModel(
            name='UserGenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('fantasy', 'Фэнтези'), ('sci_fi', 'Фантастика'), ('thriller_horror', 'Триллеры и хорроры'), ('detective', 'Детективы'), ('romance', 'Романтика'), ('classic', 'Классика'), ('prose', 'Проза'), ('history', 'История'), ('biography', 'Биографии и мемуары'), ('psychology', 'Психология'), ('self_help', 'Саморазвитие'), ('business', 'Бизнес'), ('health', 'Здоровье'), ('young_adult', 'Young Adult'), ('non_fiction', 'Нон-фикшн'), ('comics', 'Комиксы и графические романы'), ('children', 'Детям'), ('audio', 'Аудиокнига'), ('drama', 'Драма'), ('other', 'Другое')], max_length=50, verbose_name='Жанр')),
                ('weight', models.IntegerField(default=0, help_text='1 для предпочтительных, -1 для нежелательных жанров', verbose_name='Вес предпочтения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_genre_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жанровое предпочтение',
                'verbose_name_plural': 'Жанровые предпочтения',
                'unique_together': {('user', 'genre')},
            },
        ),
    ]
