# Generated by Django 5.2 on 2025-05-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_add_is_approved'),
        ('books', '0003_quote'),
    ]

    operations = [
    ]
