# Generated by Django 5.2 on 2025-06-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_add_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Фэнтези'), ('sci_fi', 'Фантастика'), ('thriller_horror', 'Триллеры и хорроры'), ('detective', 'Детективы'), ('romance', 'Романтика'), ('classic', 'Классика'), ('prose', 'Проза'), ('history', 'История'), ('biography', 'Биографии и мемуары'), ('psychology', 'Психология'), ('self_help', 'Саморазвитие'), ('business', 'Бизнес'), ('health', 'Здоровье'), ('young_adult', 'Young Adult'), ('non_fiction', 'Нон-фикшн'), ('comics', 'Комиксы и графические романы'), ('children', 'Детям'), ('audio', 'Аудиокнига'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Жанр'),
        ),
        migrations.CreateModel(
            name='GlobalCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название коллекции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('books', models.ManyToManyField(related_name='global_collections', to='books.book', verbose_name='Книги')),
            ],
            options={
                'verbose_name': 'Глобальная коллекция',
                'verbose_name_plural': 'Глобальные коллекции',
            },
        ),
    ]
