# Generated by Django 5.2 on 2025-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_genre_globalcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Фэнтези'), ('sci_fi', 'Фантастика'), ('thriller_horror', 'Триллеры и хорроры'), ('detective', 'Детективы'), ('romance', 'Романтика'), ('classic', 'Классика'), ('prose', 'Проза'), ('history', 'История'), ('biography', 'Биографии и мемуары'), ('psychology', 'Психология'), ('self_help', 'Саморазвитие'), ('business', 'Бизнес'), ('health', 'Здоровье'), ('young_adult', 'Young Adult'), ('non_fiction', 'Нон-фикшн'), ('comics', 'Комиксы и графические романы'), ('children', 'Детям'), ('audio', 'Аудиокнига'), ('drama', 'Драма'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Жанр'),
        ),
    ]
