# Generated by Django 5.2 on 2025-06-04 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Код языка')),
                ('name', models.CharField(max_length=50, verbose_name='Название языка')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_goal', models.CharField(choices=[('fun', 'Отдых/развлечение'), ('inspire', 'Вдохновение/идеи'), ('skill', 'Проф-рост'), ('study', 'Учёба/исследование')], max_length=10, verbose_name='Цель чтения')),
                ('mood_tags', models.JSONField(default=list, verbose_name='Предпочитаемая атмосфера')),
                ('reading_frequency', models.FloatField(choices=[(0.5, '< 1 книг/мес'), (1.5, '1–2 книг/мес'), (4.0, '3–5 книг/мес'), (6.0, '> 5 книг/мес')], verbose_name='Частота чтения')),
                ('content_filters', models.JSONField(default=list, verbose_name='Контент-фильтры')),
                ('fav_authors', models.ManyToManyField(related_name='favorite_of_users', to='books.author', verbose_name='Любимые авторы')),
                ('fav_books', models.ManyToManyField(related_name='favorite_of_users', to='books.book', verbose_name='Любимые книги')),
                ('original_languages', models.ManyToManyField(to='books.language', verbose_name='Предпочитаемые языки оригинала')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserGenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('fantasy', 'Фэнтези'), ('sci_fi', 'Фантастика'), ('thriller_horror', 'Триллеры и хорроры'), ('detective', 'Детективы'), ('romance', 'Романтика'), ('classic', 'Классика'), ('prose', 'Проза'), ('history', 'История'), ('biography', 'Биографии и мемуары'), ('psychology', 'Психология'), ('self_help', 'Саморазвитие'), ('business', 'Бизнес'), ('health', 'Здоровье'), ('young_adult', 'Young Adult'), ('non_fiction', 'Нон-фикшн'), ('comics', 'Комиксы и графические романы'), ('children', 'Детям'), ('audio', 'Аудиокнига'), ('drama', 'Драма'), ('other', 'Другое')], max_length=50)),
                ('weight', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жанровые предпочтения пользователя',
                'verbose_name_plural': 'Жанровые предпочтения пользователей',
                'unique_together': {('user', 'genre')},
            },
        ),
    ]
