# Generated by Django 5.2 on 2025-06-04 20:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_language_userprofile_usergenrepreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='original_languages',
        ),
        migrations.AlterUniqueTogether(
            name='usergenrepreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergenrepreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fav_authors',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fav_books',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='book',
            name='moderation_notes',
            field=models.TextField(blank=True, verbose_name='Заметки модератора'),
        ),
        migrations.AddField(
            model_name='book',
            name='needs_moderation',
            field=models.BooleanField(default=True, help_text='Отметьте, если книга требует дополнительной проверки из-за неполных данных', verbose_name='Требует проверки модератором'),
        ),
        migrations.AddField(
            model_name='book',
            name='openlibrary_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID в OpenLibrary'),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('description', models.TextField(blank=True, verbose_name='Описание жанра')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgenres', to='books.genre', verbose_name='Родительский жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='UserGenrePreference',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
