# Generated by Django 5.2 on 2025-06-09 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_userprofile_original_languages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('custom', 'Пользовательская'), ('genre', 'По жанру'), ('author', 'По автору'), ('theme', 'Тематическая'), ('period', 'По периоду')], default='custom', max_length=20, verbose_name='Тип подборки')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='collection_covers/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичная')),
                ('featured', models.BooleanField(default=False, verbose_name='Избранная')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('books', models.ManyToManyField(related_name='collections', to='books.book', verbose_name='Книги')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подборка',
                'verbose_name_plural': 'Подборки',
                'ordering': ['-created_at'],
            },
        ),
    ]
