# Generated by Django 5.2 on 2025-06-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_rejection_reason_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='moderation_comment',
            field=models.TextField(blank=True, verbose_name='Комментарии для модерации'),
        ),
    ]
