# Generated by Django 5.2 on 2025-06-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_needs_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Внешний ID книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='read_sources',
            field=models.JSONField(blank=True, default=dict, verbose_name='Источники для чтения'),
        ),
        migrations.AddField(
            model_name='book',
            name='site_rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг на сайте'),
        ),
    ]
