# Generated by Django 5.2 on 2025-06-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_book_id_book_pages_book_read_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spoiler',
            field=models.BooleanField(default=False, verbose_name='Содержит спойлер'),
        ),
    ]
