# Generated by Django 5.2 on 2025-06-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_review_spoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='wiki_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на Wikipedia'),
        ),
    ]
