# Generated by Django 5.2 on 2025-06-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_collection_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='read_sources',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='Международный стандартный книжный номер', max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='online_sources',
            field=models.JSONField(blank=True, default=dict, help_text='Укажите ссылки на сайты, где можно прочитать книгу онлайн', verbose_name='Ссылки для чтения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='Обязательное поле. Выберите одного или нескольких авторов.', related_name='books', to='books.author', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Добавьте описание книги.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(default=1, help_text='Обязательное поле. Укажите общее количество страниц в книге.', verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Обязательное поле. Введите название книги.', max_length=255, verbose_name='Название'),
        ),
    ]
