# Generated by Django 5.2 on 2025-06-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_options_remove_book_read_sources_and_more'),
        ('books', '0017_fix_empty_slugs'),
    ]

    operations = [
    ]
